water/urls.py
from django.contrib import admin
from django.urls import path
from clients.views import *
from core.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', contacts),
    path('about/', about),
    path('', products_list),
    path('makers/', makers_list),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('orders/', OrderListView.as_view(), name="order-list"),
    path('order/create/', OrderCreateView.as_view(), name='order-create'),
    path('order/update/<int:pk>/', OrderUpdateView.as_view(), name='order-update'),
    path('order/delete/<int:pk>/', OrderDeleteView.as_view(), name='order-delete'),
    path('order/<int:pk>/', OrderInfoView.as_view(), name="order-info"),
    path('signin/', LoginView.as_view(), name="sign-in"),
    path('signout/', LogoutView.as_view(), name="sign-out"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from email.policy import default
from django.contrib.auth.models import User
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    active = models.BooleanField(default=False)
    bottles_ordered = models.IntegerField(default=1)
    photo = models.ImageField(
        verbose_name="фотография",
        upload_to='photo',
        null=True,
        blank=True
    )


class Order(models.Model):
    client = models.ForeignKey(
        to=Client, null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="order"
    )

    created_at = models.DateTimeField(
        verbose_name="Дата и время создания заказа",
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        verbose_name="Дата и время изменения заказа",
        auto_now=True,
    )

    description = models.TextField(null=True, blank=True, help_text="Вы можете добавить описание")
    name = models.CharField(max_length=255, help_text="Введите Ваше имя")
    contacts = models.CharField(max_length=255, help_text="Введите Ваш номер телефона, адрес электронной почты или "
                                                          "социальной сети")
    finished = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} - {self.contacts}"

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

core/models.py
from django.db import models
from clients.models import Order


class Bottle(models.Model):
    volume = models.IntegerField(default=10, null=True, blank=True)
    maker = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    expired = models.BooleanField(default=False, null=True, blank=True)


class BottlesCount(models.Model):
    bottle = models.ForeignKey(to=Bottle, on_delete=models.SET_NULL, null=True, blank=True, related_name="bottle_count")
    count = models.IntegerField(default=1)
    order = models.ForeignKey(to=Order, on_delete=models.SET_NULL, null=True, blank=True, related_name="bottle_count")

    def __str__(self):
        return f"{self.bottle} - {self.count} - {self.order}"

clients/forms.py
from django import forms
from .models import Order, Client


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["name", "contacts", "description"]


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'address']

core/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255)

clients/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Client, Order


class ClientListView(ListView):
    model = Client
    template_name = 'clients.html'


class OrderListView(ListView):
    model = Order
    template_name = 'order_list.html'


class OrderCreateView(CreateView):
    model = Order
    template_name = 'order_create.html'
    fields = ["name", "contacts", "description"]
    success_url = "/orders/"


class OrderUpdateView(UpdateView):
    model = Order
    template_name = 'order_update.html'
    fields = ["name", "contacts", "description"]
    success_url = "/orders/"


class OrderDeleteView(DeleteView):
    model = Order
    template_name = 'order_delete.html'
    fields = ["name", "contacts", "description"]
    success_url = "/orders/"


class OrderInfoView(DetailView):
    model = Order
    template_name = "order_info.html"

core/views.py
from django.shortcuts import render, HttpResponse, redirect
# core/views.py
from .models import Bottle
from django.views import View
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm
from django.contrib.auth.models import AnonymousUser


def contacts(request):
    return render(request, 'core/contacts.html')


def about(request):
    return render(request, 'about.html')


def makers_list(request):
    context = {}
    # SELECT * FROM Bottle
    bottles_list = Bottle.objects.all()
    context["bottles_list"] = bottles_list
    html_page = render(request, 'makers.html', context)
    return html_page


def products_list(request):
    return render(request, 'products.html')


class LoginView(View):
    def get(self, request):
        context = {"form": LoginForm()}
        return render(request, 'auth/sign_in.html', context)

    def post(self, request, *args, **kwargs):
        data = request.POST
        user_login = data["username"]
        password = data["password"]
        user = authenticate(request, username=user_login, password=password)
        if user is not None:
            login(request, user)
            return redirect(products_list)
        else:
            return HttpResponse("Не верный логин или пароль")


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(products_list)

clients/templates/base.html
<!doctype html>
{% load static %}
<html lang =“en-us”>
<head>
    <title>Сайт воды</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div class="container">
        <nav>
            <a href="/products/">Продукция &nbsp;&nbsp;&nbsp;</a>
            <a href="/about/">О нас &nbsp;&nbsp;&nbsp;</a>
            <a href="/contacts/">Контакты &nbsp;&nbsp;&nbsp;</a>
            <a href="/clients/">Наши клиенты</a>
        </nav>
        <div id="page">
            {% block page %}

            {% endblock %}
        </div>
        <footer>
            График работы:<br/>
            Понедельник - суббота: с 9-00 до 18-00, без перерыва на обед.<br/>
            Воскресенье: с 9-00 до 17-00, без перерыва на обед.<br/>
            По вопросам касающихся гарантийного обслуживания звоните в технический отдел 0555 700 191<br/>
            Жалобы и пожелания просим писать на marketing@alliance.web.kg<br/>
        </footer>
    </div>
</body>

clients/templates/clients.html
{% extends 'base.html' %}
{% block page %}<br/>
{% for client in client_list %}
        <div>
            Имя: {{ client.name }}<br/>
            Адрес: {{client.address}}<br/>
            Кол-во бутылей: {{ client.bottles_ordered}}<br/>
            Фотография:
            {% if client.photo %}
                <br/>
                <img src="{{ client.photo.url }}" alt="нет фото">
            {% endif %}
        </div>
    <hr>
    {% endfor %}
{% endblock %}

clients/templates/order_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% block page %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button>Добавить заказ</button>
    </form>
{% endblock %}

clients/templates/order_delete.html
{% extends 'base.html' %}
{% block page %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}<br/>
        <div>Подтвердите удаление</div><br/>
        <button>Удалить</button>
    </form>
{% endblock %}

clients/templates/order_info.html
{% extends 'base.html' %}
{% block page %}<br/>
    <div>
        <hr>
        <div>Имя: {{ object.name }}</div>
        <div>Контакты: {{ object.contacts }}</div>
        <div>Комментарии: {{ object.description }}</div>
        <div>Статус: {{ object.finished }}</div>
        <div>Клиент: {{ object.client.name }}</div>
        <hr>
    </div>
{% endblock %}

clients/templates/order_list.html
{% extends 'base.html' %}
{% block page %}<br/>
    <div><nav><a href="{% url 'order-create' %}">Добавить заказ</a></nav></div>
    <hr>
    <h1>Список заказов</h1><hr>
    {% for order in order_list %}
    <a href="/order/{{ order.id }}/"><div>Заказ:  {{  order.name }}</div></a><br/>
    <a href="/order/update/{{ order.id }}/">Изменить</a>
    <a href="/order/delete/{{ order.id }}/">Удалить</a>
    <hr>
    {% endfor %}
{% endblock %}

clients/templates/order_update.html
{% extends 'base.html' %}
{% block page %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>Подтвердите изменения</div><br/>
        <button>Изменить</button>
    </form>
{% endblock %}

core/templates/about.html
{% extends 'base.html' %}
{% block page %}
    <div>
        <br/>
        <br/>
        <h1>О компании</h1><br/>
        ОсОО Top Notch Distribution является производителем природной питьевой воды Corona ice. Компания была <br/>
        создана в 2009 году, и продолжает активно развиваться, внедряет современные технологии в производство, и <br/>
        расширяет с каждым днем ассортимент товаров. Установите мобильное приложение для заказа всего ассортимента <br/>
        товаров 24/7 без звонка!!! Доставка в течении следующего рабочего дня! Цены оптового склада. Оператор <br/>
        приложения 0 999 006464. Жми сюда!<br/>
    </div>
    <hr>
{% endblock %}

core/templates/base.html
<!doctype html>
{% load static %}
<html lang =“en-us”>
<head>
    <title>Сайт воды</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="icon" sizes="192x192" href="{% static 'log-water.jpg' %}">
</head>
<body>
    <div class="container">
        <nav>
            <a href="/">Продукция &nbsp;&nbsp;&nbsp;</a>
            <a href="/clients">Наши клиенты</a>
            <a href="{% url 'order-list' %}">Список заказов</a>
            <a href="/about/">О нас &nbsp;&nbsp;&nbsp;</a>
            <a href="/contacts/">Контакты &nbsp;&nbsp;&nbsp;</a>
            <a href="/signin/">Войти</a>
            <a href="/signout/">Выйти</a>
        </nav>
        <hr>
        <hr>
        <h2> Приветствую Вас, {{ request.user }}</h2>
        <hr>
        <hr>
        <div id="page">
            {% block page %}

            {% endblock %}
        </div>
        <footer>
            <br/>
            График работы:<br/>
            Понедельник - суббота: с 9-00 до 18-00, без перерыва на обед.<br/>
            Воскресенье: с 9-00 до 17-00, без перерыва на обед.<br/>
            По вопросам касающихся гарантийного обслуживания звоните в технический отдел 0555 700 191<br/>
            Жалобы и пожелания просим писать на marketing@alliance.web.kg<br/>
        </footer>
    </div>
</body>

core/templates/core/contacts.html
{% extends 'base.html' %}
{% block page %}
    <div>
        <br/>
        <br/>
        <h1>Контакты</h1><br/>

        0312 98-69-69<br/>
        0707 89-15-88<br/>
        0550 89-15-88 0555 89-15-88<br/>
        0550 89-15-88, 0555 89-15-88<br/>
        coronaice_19@inbox.ru<br/>
        с.Пригородное ул.Сибирская 22<br/>
    </div>
    <hr>
{% endblock %}

core/templates/makers.html
{% extends 'base.html' %}
{% block page %}
   {% for bottle in bottles_list %}
        <div>{{ bottle.maker }}</div>
    {% endfor %}

{% endblock %}

core/templates/products.html
{% extends 'base.html' %}
{% block page %}

        <hr>
        <h1>Продукция</h1><br/>
        <div>Вода Corona Ice негазированная для г.Бишкек, + 10 сом для регионов</div>
        <img src="http://www.corona.kg/upload/catalog/products/1.png" alt="">
        <div>135-155 сом</div>
        <button>Заказать</button><br/><br/>
        <div>Вода Corona Ice негазированная</div>
        <img src="http://www.corona.kg/upload/catalog/products/2.png" alt="">
        <div>82 сом</div>
        <button>Заказать</button><br/><br/>
        <div>Вода "Corona Ice"  6л (New)</div>
        <img width="50" src="http://www.corona.kg/upload/catalog/products/9.png" alt="">
        <div>52 сом</div>
        <button>Заказать</button><br/><br/>
        <div>Вода Corona Ice газированная 0,5л х15</div>
        <img src="http://www.corona.kg/upload/catalog/products/3.png" alt="">
        <div >17 сом</div>
        <button>Заказать</button><br/><br/>
        <div>Вода Corona Ice негазированная 1,0л х8</div>
        <img src="http://www.corona.kg/upload/catalog/products/4.png" alt="">
        <div>21 сом</div>
        <button>Заказать</button><br/><br/>
        <hr>
{% endblock %}